### ISSUE TITLE
Request for English Version of Official Documentation

### ISSUE THREAD

**Issue by developersharif** [swoole/docs#30]
Dear Swoole team,

I would like to request an English version of the official documentation. Currently, the documentation is not available in English, and it would be immensely helpful for non-Chinese-speaking users like me.

**Comment by jingjingxyk** [comment]
1. Using Google Translate Official Documents。

2. Using the browser's built-in translation plugin

3. Using the browser extension  plugin:  https://github.com/FilipePS/Traduzir-paginas-web

> Official Document URL  :  https://wiki.swoole.com/#/  

> Official Document Source Code
>> 1. `git clone https://github.com/swoole/docs.git`  
>> 2.  `cd  docs/zh-ch/`  
>> 3. `php -S 0.0.0.0:9503 -t .`    OR  `docker run --rm --name swoole-docs  -v $(pwd):/usr/share/nginx/html/  -p 9503:80  nginx:1.25-alpine`
>> 4.  browser open url： http://0.0.0.0:9503


## 

方法一： 使用谷歌翻译, 将 简体中文 翻译为 英文
方法二： 使用浏览器内置翻译功能
方法二： 使用浏览器翻译扩展： https://github.com/FilipePS/Traduzir-paginas-web


> 文档地址一： 浏览器打开地址： https://wiki.swoole.com/#/  

> 文档地址二（源码）：  
>> 1. `git clone https://github.com/swoole/docs.git`  
>> 2.  `cd  docs/zh-ch/`  
>> 3. `php -S 0.0.0.0:9503 -t .`  或者 `docker run --rm --name swoole-docs  -v $(pwd):/usr/share/nginx/html/  -p 9503:80  nginx:1.25-alpine`
>> 4.  浏览器打开地址： http://0.0.0.0:9503



![image](https://github.com/swoole/docs/assets/6836228/ae7582b5-eabf-4a68-b66e-8a6b3c1c102c)

**Comment by matyhtf** [comment]
@developersharif  Done.
