### ISSUE TITLE
进程/线程结构图 404

### ISSUE THREAD

**Issue by lwlwilliam** [swoole/docs#32]
zh-ch/server/init.md 的 process_structure_2 没有跟其它图一样用 cdn，导致第二张[进程/线程结构图](https://wiki.swoole.com/_images/server/process_structure_2.png) 404

**Comment by jingjingxyk** [comment]
应该是部署问题： https://github.com/swoole/docs/blob/main/zh-ch/_images/server/process_structure_2.png

**Comment by lwlwilliam** [comment]
> 应该是部署问题： https://github.com/swoole/docs/blob/main/zh-ch/_images/server/process_structure_2.png

嗯，也可以用 github 的。我就是看源码图片都用的 cdn，就这图用了相对路径

**Comment by jingjingxyk** [comment]
本地部署文档： https://github.com/swoole/docs/issues/28
